# ------------------------------------------------------------------------------
# Generate template excel sheets from a data model using schematic
# ------------------------------------------------------------------------------
name: generate-templates
on:
  repository_dispatch:
    types: generate_templates
  workflow_dispatch:
  
jobs:
  auto-open-pr:
    runs-on: ubuntu-latest
    steps:        
      - name: Test
        run: echo 'Successfully triggered workflow via repo dispatch!'
        
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Checkout schematic
        uses: actions/checkout@v3
        with:
          repository: 'Sage-Bionetworks/schematic'
          path: './schematic'
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pip
          
      - name: Install python dependencies
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: |
          cd schematic
          poetry install
     
      - name: Test schematic
        run: |
          cd schematic
          poetry run schematic init -c schematic_config.yml